# Generated by Django 2.0.6 on 2019-06-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('progress', 'progress'), ('done', 'done')], default='progress', max_length=15),
        ),
    ]
