# Generated by Django 2.0.6 on 2019-06-23 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_winner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
